# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 942b4399ccc5a3839921eab15c47fcf4102edcf4d29215bc121979c9a202df0ce28672d2230c34e26ec307a2f32a10f6a6b01be5a37d8ad31ee59d0a508b0cf8

test:
  secret_key_base: 18f0131e75781cb1549b3fff5f18b7badcf3b53b0e9bd5f29e8e38f1cff0df3ab9116fd938561490b565e56e207cfd6bbd9270f8d3dee0fa2ad13feeb625606c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
